services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    profiles: [devlocal]
    command: [ "start-dev", "--import-realm" ]
    volumes: 
      -  ./docker/realm-config.json:/opt/keycloak/data/import/realm-config.json 
    environment:
      -  KEYCLOAK_ADMIN=admin 
      -  KEYCLOAK_ADMIN_PASSWORD=admin 
      -  KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config.json  
    ports:
      - "7080:8080"